In [15]:
import pandas as pd
import os
import numpy as np
from sqlalchemy import create_engine

In [16]:
file = os.path.join('ht_data.csv')

In [17]:
file_df = pd.read_csv(file)
organized_df = file_df.dropna(axis='columns').sort_values('yearOfRegistration')
little_df = organized_df.drop(['isAbduction', 'majorityStatus', 'RecruiterRelationship', 'recruiterRelationIntimatePartner', 'recruiterRelationFriend', 'recruiterRelationFamily', 'recruiterRelationOther', 'recruiterRelationUnknown', 'isForcedMarriage', 'isForcedMilitary', 'isOrganRemoval', 'typeOfSexProstitution', 'typeOfSexPornography', 'typeOfSexRemoteInteractiveServices','typeOfSexPrivateSexualServices', 'typeOfSexConcatenated'], axis=1)
#little_df = little_df.replace(to_replace=[-99,'-99'], value=np.nan)

In [18]:
little_df = little_df.rename(columns={'yearOfRegistration': 'Year Identified',
 'Datasource': 'Means of Identification',
 'gender': 'Gender',
 'ageBroad': 'Age Range',
 'majorityStatusAtExploit': 'Age at Exploitaion',
 'majorityEntry': 'Age Grooming Process',
 'citizenship': 'Citizenship',
 'meansOfControlDebtBondage': 'Method of Control: Debt Bondage',
 'meansOfControlTakesEarnings': 'Method of Control: Earnings Taken',
 'meansOfControlRestrictsFinancialAccess': 'Method of Control: Restricted Financial Access',
 'meansOfControlThreats': 'Method of Control: Threats',
 'meansOfControlPsychologicalAbuse':'Method of Control: Psychological Abuse',
 'meansOfControlPhysicalAbuse': ' Method of Control: Physical Abuse',
 'meansOfControlSexualAbuse': 'Method of Control: Sexual Abuse',
 'meansOfControlFalsePromises': 'Method of Control: False Promises',
 'meansOfControlPsychoactiveSubstances': 'Method of Control: Psychoactive Substances',
 'meansOfControlRestrictsMovement':'Method of Control: Restricted Movement ',
 'meansOfControlRestrictsMedicalCare':'Method of Control: Restricted Medical Care ',
 'meansOfControlExcessiveWorkingHours':'Method of Control: Extreme Work Hours',
 'meansOfControlUsesChildren':'Method of Control: Children of Victim',
 'meansOfControlThreatOfLawEnforcement':'Method of Control: Fear of Law Enforcement ',
 'meansOfControlWithholdsNecessities':'Method of Control: Witheld Necesities',
 'meansOfControlWithholdsDocuments':'Method of Control: Documentation Witheld',
 'meansOfControlOther':'Method of Control: Other',
 'meansOfControlNotSpecified':'Method of Control: Unspecified ',
 'meansOfControlConcatenated':'Method of Control: Multiple Methods of Control',
 'isForcedLabour': 'Labor Trafficking',
 'isSexualExploit': 'Sex Trafficking' ,
 'isOtherExploit': 'Human Trafficking: Other',
 'isSexAndLabour': 'Sex and Labour Trafficking',
 'typeOfExploitConcatenated': 'Multiple Types of Exploitation',
 'typeOfLabourAgriculture': 'Type: Agriculture',
 'typeOfLabourAquafarming': 'Type: Aquafarming',
 'typeOfLabourBegging': 'Type: Begging',
 'typeOfLabourConstruction': 'Type: Construction Labour',
 'typeOfLabourDomesticWork': 'Type: Domestic Work',
 'typeOfLabourHospitality':'Type: Hospitality Labour',
 'typeOfLabourIllicitActivities': 'Type: Illicit Activites',
 'typeOfLabourManufacturing': 'Type: Manufacturing',
 'typeOfLabourMiningOrDrilling': 'Type: Mining or Drilling',
 'typeOfLabourPeddling': 'Type: Peddling',
 'typeOfLabourTransportation':'Type: Transportation',
 'typeOfLabourOther':'Type: Other',
 'typeOfLabourNotSpecified': 'Type: Unspecified',
 'typeOfLabourConcatenated': 'Type: Multiple',
'CountryOfExploitation': 'Country of Exploitation'})
little_df

,Year Identified,Means of Identification,Gender,Age Range,Age at Exploitaion,Age Grooming Process,Citizenship,Method of Control: Debt Bondage,Method of Control: Earnings Taken,Method of Control: Restricted Financial Access,...,Type: Hospitality Labour,Type: Illicit Activites,Type: Manufacturing,Type: Mining or Drilling,Type: Peddling,Type: Transportation,Type: Other,Type: Unspecified,Type: Multiple,Country of Exploitation
0,2002,Case Management,-99,-99,-99,-99,-99,-99,-99,-99,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
744,2002,Case Management,Female,24--26,-99,-99,MD,-99,-99,-99,...,0,0,0,0,0,0,0,0,-99,-99
745,2002,Case Management,Female,24--26,-99,-99,MD,-99,-99,-99,...,0,0,0,0,0,0,0,0,-99,-99
746,2002,Case Management,Female,24--26,-99,-99,MD,-99,-99,-99,...,0,0,0,0,0,0,0,0,-99,-99
747,2002,Case Management,Female,24--26,-99,-99,MD,-99,-99,-99,...,0,0,0,0,0,0,0,0,-99,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54583,2018,Case Management,Female,-99,Minor,-99,KH,0,0,-99,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,KH
54582,2018,Case Management,Female,-99,Minor,-99,KH,0,0,-99,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,KH
54581,2018,Case Management,Female,-99,Minor,-99,KH,0,0,-99,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,KH
54588,2018,Case Management,Female,-99,Minor,-99,KH,0,0,-99,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,KH
55433,2018,Case Management,Male,-99,Adult,-99,KH,0,0,-99,...,-99,-99,-99,-99,-99,-99,-99,-99,-99,KH

In [19]:
#establish SQL Connection
pg_user = 'postgres'
pg_password = 'Dhanista#4'
db_name = 'ETL-Project'

connection_string = f"{pg_user}:{pg_password}@localhost:5432/{db_name}"
engine = create_engine(f'postgresql://{connection_string}')

In [45]:
file_codes = os.path.join('countries_codes_and_coordinates.csv')
file_codes_df = pd.read_csv(file_codes)
file_codes_df.drop(['Numeric code', 'Latitude (average)', 'Longitude (average)'], axis = 1)
file_codes_df.dtypes

Country                object
Alpha-2 code           object
Alpha-3 code           object
Numeric code           object
Latitude (average)     object
Longitude (average)    object
dtype: object

In [60]:
alpha_list_a = file_codes_df["Alpha-2 code"].tolist()

alpha_list_b = file_codes_df["Alpha-3 code"].tolist()

a= map(alpha_list_a[1],'B')
print(a)

<map object at 0x11d7165d0>